name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        
      - name: Get Permissions
        run: chmod +x ./gradlew

      - name: Lint
        run: ./gradlew lintDebug

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: report.html
          path: app/build/reports/lint-results-debug.html
